In [38]:
import pandas as pd
import numpy as np


# hierarchical indexing

In [15]:
s1 = pd.Series(np.arange(10),index=[list('aaabbbcccc'),[1,2,3,1,2,3,1,2,3,4]])

In [27]:
s1.index.name = ['key1','key2']

In [28]:
s1

a  1    0
   2    1
   3    2
b  1    3
   2    4
   3    5
c  1    6
   2    7
   3    8
   4    9
dtype: int32

In [17]:
s1[:,2]

a    1
b    4
c    7
dtype: int32

In [19]:
s1.loc['a',:2]

a  1    0
   2    1
dtype: int32

In [20]:
s1.unstack()

1    2    3    4
a  0.0  1.0  2.0  NaN
b  3.0  4.0  5.0  NaN
c  6.0  7.0  8.0  9.0

In [21]:
s1.unstack().stack() # stack 堆栈

a  1    0.0
   2    1.0
   3    2.0
b  1    3.0
   2    4.0
   3    5.0
c  1    6.0
   2    7.0
   3    8.0
   4    9.0
dtype: float64

In [25]:
df1 = pd.DataFrame(np.arange(12).reshape((4,3)),
                  index = [['a','a','b','b'],[1,2,1,2]],
                  columns = [['ohio','ohio','colifornia'],['green','red','red']])
df1

ohio     colifornia
    green red        red
a 1     0   1          2
  2     3   4          5
b 1     6   7          8
  2     9  10         11

In [30]:
df1.index.names = ['key1','key2']
df1.columns.names = ['state','color']

color      green  red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [40]:
df1.swaplevel('key1','key2').sort_index()

state      ohio     colifornia
color     green red        red
key2 key1                     
1    a        0   1          2
     b        6   7          8
2    a        3   4          5
     b        9  10         11

In [39]:
df1.sort_index(level =1)

state      ohio     colifornia
color     green red        red
key1 key2                     
a    1        0   1          2
b    1        6   7          8
a    2        3   4          5
b    2        9  10         11

In [45]:
df1.sum(level = 'state',axis = 1)

state      colifornia  ohio
key1 key2                  
a    1              2     1
     2              5     7
b    1              8    13
     2             11    19

In [47]:
df2 = pd.DataFrame({'a':np.arange(7),
                'b':range(7,14),
                'c':['one'] * 3+ ['two']*4,
                'd':[1,2,3,1,2,3,4]})
df2.set_index(['c','d']) 

a   b
c   d       
one 1  0   7
    2  1   8
    3  2   9
two 1  3  10
    2  4  11
    3  5  12
    4  6  13

In [50]:
df2.set_index(['c','d']).reset_index()

c  d  a   b
0  one  1  0   7
1  one  2  1   8
2  one  3  2   9
3  two  1  3  10
4  two  2  4  11
5  two  3  5  12
6  two  4  6  13

# combining and merging datasets

In [57]:
df3 = pd.DataFrame({'key':list('bbacab'),
                   'data1':range(6)})
df4 = pd.DataFrame({'key':list('abd'),'data2':range(3)})

In [58]:
pd.merge(df4,df3,on = 'key',how = 'outer')

data2 key  data1
0    0.0   a    2.0
1    0.0   a    4.0
2    1.0   b    0.0
3    1.0   b    1.0
4    1.0   b    5.0
5    2.0   d    NaN
6    NaN   c    3.0

In [59]:
df5 = pd.DataFrame({'key':list('ababd'),
                   'data2':range(5)})

In [64]:
df3.merge(df5,how = 'outer',on = 'key')

data1 key  data2
0     0.0   b    1.0
1     0.0   b    3.0
2     1.0   b    1.0
3     1.0   b    3.0
4     5.0   b    1.0
5     5.0   b    3.0
6     2.0   a    0.0
7     2.0   a    2.0
8     4.0   a    0.0
9     4.0   a    2.0
10    3.0   c    NaN
11    NaN   d    4.0

In [65]:
df6 = pd.DataFrame({'key1':['foo','foo','bar'],
                   'key2':['one','two','one'],
                   'lval':[1,2,3]})
df7 = pd.DataFrame({'key1':['foo','foo','bar','bar'],
                   'key2':['one','one','one','two'],
                   'rval':[4,5,6,7]})

In [83]:
df6.merge(df7,on = 'key1',how = 'outer',suffixes = ('_left','_right'),
         copy = False,
         sort = False)

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [88]:
df8 = pd.DataFrame({'rval':range(4,7)},index = ['foo','bar','apple'])
df8.merge(df6,left_index = True,right_on = 'key1',how = 'outer')

rval   key1 key2  lval
0     4    foo  one   1.0
1     4    foo  two   2.0
2     5    bar  one   3.0
2     6  apple  NaN   NaN

In [95]:
df9 = pd.DataFrame({'rval':[4,5,6]},
                   index = [['one','foo','bar'],['foo','foo','sis']])
df9

rval
one foo     4
foo foo     5
bar sis     6

In [100]:
df6.merge(df9,left_on = ['key2','key1'],right_index = True,how='inner')
# left_on和index是按顺序匹配的，如果left_on =['key1','key2'],则为空

key1 key2  lval  rval
0  foo  one     1     4

In [118]:
df10 = pd.DataFrame({'rrval':[4,5,6]},
                   index = ['one','foo','bar'])

In [109]:
df8

rval
foo       4
bar       5
apple     6

In [111]:
df10

rval
one     4
foo     5
bar     6

In [119]:
df11 = pd.DataFrame({'orgen':[9,10,11]},
                   index = ['one','foo','bar'])

In [121]:
df8.join([df10,df11],how = 'outer') # 合并后列名必须不一样，否则报错 
                                    # 可以多个join，但是不能多个merge，多个合并默认on index
                                    # 多个合并时也可以用on，但是要保证每个df中都有on这个label

rval  rrval  orgen
apple   6.0    NaN    NaN
bar     5.0    6.0   11.0
foo     4.0    5.0   10.0
one     NaN    4.0    9.0

In [2]:
arr1 = np.arange(12).reshape((3,4))
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.concatenate([arr1,arr1],axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [8]:
s11 = pd.Series([1,2,3],index = ['a','b','c'])
s12 = pd.Series([4,5],index = ['d','e'])
s13 = pd.Series([5,6],index = ['f','g'])
pd.concat([s11,s12,s13])

a    1
b    2
c    3
d    4
e    5
f    5
g    6
dtype: int64

In [12]:
pd.concat([s11,s12,s13],axis = 1,join = 'outer') # 默认join = 'outer

0    1    2
a  1.0  NaN  NaN
b  2.0  NaN  NaN
c  3.0  NaN  NaN
d  NaN  4.0  NaN
e  NaN  5.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [27]:
pd.DataFrame(s12)

0
d  4
e  5

In [31]:
pd.merge(pd.DataFrame(s11),pd.DataFrame(s12),how = 'outer',on = 0,suffixes = ('_left','_right'))

0
0  1
1  2
2  3
3  4
4  5

In [39]:
pd.concat([s11,s12],join_axes = [['a','b','c','d']],axis = 1)

0    1
a  1.0  NaN
b  2.0  NaN
c  3.0  NaN
d  NaN  4.0

In [42]:
result1 = pd.concat([s11,s12,s13],keys = ['one','two','three'])
result1

one    a    1
       b    2
       c    3
two    d    4
       e    5
three  f    5
       g    6
dtype: int64

In [45]:
result1.unstack()

a    b    c    d    e    f    g
one    1.0  2.0  3.0  NaN  NaN  NaN  NaN
two    NaN  NaN  NaN  4.0  5.0  NaN  NaN
three  NaN  NaN  NaN  NaN  NaN  5.0  6.0

In [47]:
result2 = pd.concat([s11,s12,s13],axis = 1,keys = ['one','two','three'])
result2

one  two  three
a  1.0  NaN    NaN
b  2.0  NaN    NaN
c  3.0  NaN    NaN
d  NaN  4.0    NaN
e  NaN  5.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [85]:
df13 = pd.DataFrame(np.arange(6).reshape((3,2)) ,columns = ['one','two'],
                    index = ['a','b','c'])
df14 = pd.DataFrame(np.arange(4).reshape((2,2)) + 5,columns = ['three','four'],
                   index = ['a','c'])

In [54]:
pd.concat([df13,df14],keys = ['key1','key2'],axis = 1) # 也可以用下面的方法

key1      key2     
   one two three four
a    0   1   5.0  6.0
b    2   3   NaN  NaN
c    4   5   7.0  8.0

In [56]:
pd.concat({'level1':df13,'level2':df14},axis =1) # 如果用merge的话：

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [61]:
result4 = pd.merge(df13,df14,left_index = True,right_index=True,how = 'outer')
result4.columns = [
    ['level1','level1','level2','level2'],['one','two','three','four']]
result4

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [63]:
df13.join([df14])

one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

In [64]:
pd.concat({'level1':df13,'level2':df14},axis =1,names = ['upper','lower'])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [67]:
pd.concat([df13,df14],ignore_index = True ) # 重新排列索引

four  one  three  two
0   NaN  0.0    NaN  1.0
1   NaN  2.0    NaN  3.0
2   NaN  4.0    NaN  5.0
3   6.0  NaN    5.0  NaN
4   8.0  NaN    7.0  NaN

## combing data with overlap

In [69]:
s14 = pd.Series([1,2,3,4,np.nan],index = list('abcde'))
s15 = pd.Series([np.nan,np.nan,5,6,7],index = list('abcde'))

In [71]:
np.where(pd.isnull(s15),s15,s14) # 判断条件，满足，不满足

array([ nan,  nan,   3.,   4.,  nan])

In [73]:
s14.combine_first(s14[:2]) # 把括号内的数补入前面当中
                           # 补全时索引是一一对应的

a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [91]:
df13.index = range(len(df13))
df13

one  two
0    0    1
1    2    3
2    4    5

In [92]:
df14.index = [0,3]

In [93]:
df13.combine_first(df14)  

four  one  three  two
0   6.0  0.0    5.0  1.0
1   NaN  2.0    NaN  3.0
2   NaN  4.0    NaN  5.0
3   8.0  NaN    7.0  NaN

# reshaping and pivoting

In [95]:
df13.stack().unstack()

one  two
0    0    1
1    2    3
2    4    5

In [97]:
df15 = pd.concat([s11,s12],keys = ['key1','key2'])
df15

key1  a    1
      b    2
      c    3
key2  d    4
      e    5
dtype: int64

In [100]:
df15.unstack().stack(dropna = False)

key1  a    1.0
      b    2.0
      c    3.0
      d    NaN
      e    NaN
key2  a    NaN
      b    NaN
      c    NaN
      d    4.0
      e    5.0
dtype: float64

In [116]:
df16 = pd.DataFrame({'level1':df15,'level2':df15+10},
                    columns = pd.Index(['level1','level2'],name = 'side'),
                   )

In [154]:
df16_index = pd.Index( {'key':['key1','key1','key1','key2','key2'],
                        'letter':['a','b','c','d','e']})

In [119]:
df16

side    level1  level2
key1 a       1      11
     b       2      12
     c       3      13
key2 d       4      14
     e       5      15

In [121]:
df16.unstack()

side level1                     level2                        
          a    b    c    d    e      a     b     c     d     e
key1    1.0  2.0  3.0  NaN  NaN   11.0  12.0  13.0   NaN   NaN
key2    NaN  NaN  NaN  4.0  5.0    NaN   NaN   NaN  14.0  15.0

## pivoting long to wide format data

In [126]:
df17 = pd.read_csv('examples\\macrodata.csv')
df17.head(8)

year  quarter   realgdp  realcons  realinv  realgovt  realdpi    cpi  \
0  1959.0      1.0  2710.349    1707.4  286.898   470.045   1886.9  28.98   
1  1959.0      2.0  2778.801    1733.7  310.859   481.301   1919.7  29.15   
2  1959.0      3.0  2775.488    1751.8  289.226   491.260   1916.4  29.35   
3  1959.0      4.0  2785.204    1753.7  299.356   484.052   1931.3  29.37   
4  1960.0      1.0  2847.699    1770.5  331.722   462.199   1955.5  29.54   
5  1960.0      2.0  2834.390    1792.9  298.152   460.400   1966.1  29.55   
6  1960.0      3.0  2839.022    1785.8  296.375   474.676   1967.8  29.75   
7  1960.0      4.0  2802.616    1788.2  259.764   476.434   1966.6  29.84   

      m1  tbilrate  unemp      pop  infl  realint  
0  139.7      2.82    5.8  177.146  0.00     0.00  
1  141.7      3.08    5.1  177.830  2.34     0.74  
2  140.5      3.82    5.3  178.657  2.74     1.09  
3  140.0      4.33    5.6  179.386  0.27     4.06  
4  139.6      3.50    5.2  180.007  2.31     1.19  
5  140.2      2.68    5.2  180.671  0.14     2.55  
6  140.9      2.36    5.6  181.528  2.70    -0.34  
7  141.1      2.29    6.3  182.287  1.21     1.08

In [128]:
period = pd.PeriodIndex(year = df17.year,quarter = df17.quarter,name = 'date')
columns = pd.Index(['realgdp', 'infl', 'unemp'], name='item')
df18 = df17.reindex(columns = columns)
df18.index = period.to_timestamp('D','end')

In [136]:
df19 = df18.stack().reset_index().rename(columns = {0:'value'})
df19.head(8)

date     item     value
0 1959-03-31  realgdp  2710.349
1 1959-03-31     infl     0.000
2 1959-03-31    unemp     5.800
3 1959-06-30  realgdp  2778.801
4 1959-06-30     infl     2.340
5 1959-06-30    unemp     5.100
6 1959-09-30  realgdp  2775.488
7 1959-09-30     infl     2.740

In [145]:
df19['value2'] = np.random.randn(len(df19))

In [147]:
df19.head(6)

date     item     value    value2
0 1959-03-31  realgdp  2710.349 -2.197557
1 1959-03-31     infl     0.000 -0.246995
2 1959-03-31    unemp     5.800 -0.797347
3 1959-06-30  realgdp  2778.801  1.220089
4 1959-06-30     infl     2.340 -0.939015
5 1959-06-30    unemp     5.100 -1.115091

In [152]:
df19.set_index(['date','item']).unstack('item').head(6)

value                    value2                    
item        infl   realgdp unemp      infl   realgdp     unemp
date                                                          
1959-03-31  0.00  2710.349   5.8 -0.246995 -2.197557 -0.797347
1959-06-30  2.34  2778.801   5.1 -0.939015  1.220089 -1.115091
1959-09-30  2.74  2775.488   5.3  0.600845 -0.454387  3.108760
1959-12-31  0.27  2785.204   5.6 -2.972407 -1.318571  0.640524
1960-03-31  2.31  2847.699   5.2  0.321269 -0.071796 -0.997140
1960-06-30  0.14  2834.390   5.2  0.203522 -0.611246  0.948760

## pivoting wide to long

In [155]:
df20 = pd.DataFrame({'key':['foo','bar','baz'],
                     'A':[1,2,3],
                     'B':[4,5,6],
                     'C':[7,8,9]})
df20

A  B  C  key
0  1  4  7  foo
1  2  5  8  bar
2  3  6  9  baz

In [158]:
df21 = pd.melt(df20, ['key'])
df21

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [160]:
df22 = df21.pivot('key','variable','value')
df22

variable  A  B  C
key              
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [161]:
df22.reset_index() # 重置索引

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [175]:
df23 = pd.melt(df20,id_vars = ['key'],value_vars = ['A','B'])
df23

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [173]:
df22 = pd.melt(df20,value_vars = ['A','B','key'])
df22

variable value
0        A     1
1        A     2
2        A     3
3        B     4
4        B     5
5        B     6
6      key   foo
7      key   bar
8      key   baz

In [177]:
df23.pivot('key','variable','value')

variable  A  B
key           
bar       2  5
baz       3  6
foo       1  4